services:

  # mongod
  mongo:
    image: mongo
    container_name: mongod
    restart: always
    # necessário expor a porta, pois está rodando no WSL
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123

  # GUI
  mongo-express:
    image: mongo-express
    container_name: mongo-gui
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123
      ME_CONFIG_MONGODB_URL: mongodb://root:123@mongo:27017/
      ME_CONFIG_BASICAUTH: false
